services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    # command: ["ollama", "pull", "nomic-embed-text"] # Changed to list format
    networks:
      - rag-network

  rag:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8900:8900"
    volumes:
      - ../data:/data
      - ../app:/app
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - VECTORSTORE_DIR=/app/data/vector_store
      - API_KEY="6138c5370595af0a0cc290c84a0607ebdc868c90b5f7df354001ed22c86ea52b"
    networks:
      - rag-network

volumes:
  ollama_data:

networks:
  rag-network:
    driver: bridge