version: '3.8'

services:
  rag:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8900:8900"
    volumes:
      # - ../data:/app/data
      - ../data:/app/data
      - ../app:/app
      - ../scripts:/app/scripts
      - ../tests:/app/tests
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    # gpu support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data: